### ISSUE TITLE
replies block is not working

### ISSUE THREAD

**Issue by anuragaryan** [muffinista/chatterbot#44]
```ruby
replies do |tweet|
  puts "It's a tweet!"
end
```
Even something as simple as the above code is not working. 

Can someone else verify too?

**Comment by muffinista** [comment]
Can you let me know what version of the code you are running? Also, if you could post a more complete example of your code  (without credentials) that would be helpful.

**Comment by anuragaryan** [comment]
chatterbot (2.0.2)
```ruby
favorited do |user, tweet|
  reply "@#{user.screen_name} thanks for the like!", tweet
end
followed do |user|
  tweet "@#{user.screen_name} just followed me! You get a followback too."
  follow user
end
replies do |tweet|
  puts "checking for replies to my tweets and mentions of me"
  lastfmapi = ""
  track = tweet.text.gsub(/@WhoSangThis/,'')
  lastfmurl = "http://ws.audioscrobbler.com/2.0/?method=track.search&track=#{track}&api_key=#{lastfmapi}&format=json&limit=3"
  data = open(lastfmurl).read
  json = JSON.parse(data)
  puts JSON.pretty_generate(data)
  if !json["results"]["trackmatches"].has_key?("track")
      reply "#USER# Sorry, song not found.", tweet
      continue
  end
  result ="#USER# "
  json["results"]["trackmatches"].each do |tracks|
      result = result + "#{tracks["name"]} by #{tracks["artist"]}. \n"
  end
  reply result, tweet
end
```

The other two blocks are working fine, but the replies block is not working. Even the puts statement inside the replies block is not getting accessed.

**Comment by muffinista** [comment]
OK, this is less of a bug and more of a poorly documented issue that I will try and do a better job of addressing. But for the moment, your problem is that your usage of the `followed` block requires using the streaming API, but the `replies` block won't run in that situation. What you need to do is add a `home_timeline` block, and within that, look for mentions of the bot. I usually do something like this:

```
home_timeline do |tweet|
  next if tweet.retweeted_status? || tweet.text !~ /BOTNAME/i
  # actual code here
end
```

(replace BOTNAME with the name of your bot). That will ignore retweets of your bot and any tweet that doesn't mention the bot.

Sorry for the confusion! I'll try and clean this up in the future.

**Comment by anuragaryan** [comment]
Thanks a lot for the reply. :smile:  :+1:
